name: Pylint
run-name: ${{ github.actor }} is on practice session M1-4-2-CI-Practice
on: [push]
jobs:

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Preliminary build of docker image
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: "ci-practice:pre-image"
      - 
        name: Run Trivy vulnerability scanner on 'pre-image'
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'ci-practice:pre-image'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
      -
        name: Build docker and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "ymatev/ci-practice:${{ github.sha }}"
