name: Pylint
run-name: ${{ github.actor }} is on practice session M1-4-2-CI-Practice
on: [push]
jobs:

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and NO push
        uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: "ymatev/ci-practice:test-image"

      -
        name: Test (list) test-image
        run: |
          docker images

      - 
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'ymatev/ci-practice:test-image'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'

      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "ymatev/ci-practice:${{ github.sha }}"
    

      # -
      #   name: Debug step
      #   run: |
      #       echo "Branch: ${{ github.ref }}"
      #       echo "Sha: ${{ github.sha }}"
      #       env