name: Pylint
run-name: ${{ github.actor }} is testing Pylint
on: 
  push:
    paths:
      - 'app/**.py'
  
  pull_request:
    branches:    
      - 'feature/**'

jobs:
  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  code-checker-pylint2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - run: pip install pylint -r app/requirements.txt
      - run: pylint **/*.py